FROM python:3.9-slim

ENV DB_HOST=mysql
ENV DB_USER=${MYSQL_USER}
ENV DB_NAME=${MYSQL_DATABASE}
ENV DB_PASSWORD=${MYSQL_PASSWORD}

RUN mkdir /code
WORKDIR /code
COPY requirements.txt .
RUN pip install --user -r requirements.txt
COPY main.py .
ENV PYTHONPATH="$PYTHONPATH:/code"
CMD ["python", "/code/main.py"]